import sys # Moved import sys to the top
import os # Moved import os to the top

# Adjust sys.path to allow direct execution and importing from 'chatbot' package
current_script_path = os.path.abspath(__file__)
chatbot_dir = os.path.dirname(current_script_path)
project_root = os.path.dirname(chatbot_dir)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import json
from chatbot.llm_manager import get_llm
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.pydantic_v1 import BaseModel, Field # For defining the desired JSON structure
from typing import Optional, Dict

# Define the desired output structure for the LLM using Pydantic
class LLMResponseFormat(BaseModel):
    intent: str = Field(description="The user's intent. Must be one of: 'track_order', 'cancel_order', 'greeting', 'goodbye', 'unknown'.")
    entities: Optional[Dict[str, str]] = Field(default_factory=dict, description="Extracted entities. For 'track_order' or 'cancel_order', should include 'order_id' if found.")
    # raw_llm_response: Optional[str] = Field(default="", description="The raw text response from the LLM, for debugging.") # Optional

# Global LLM instance and parser to avoid reinitialization on every call in a real app
# However, for this script structure, get_llm() might be called each time get_llm_response is.
# In a more complex app, you'd initialize llm and parser once.
llm = None
parser = None

def initialize_llm_and_parser():
    global llm, parser
    if llm is None: # Initialize only if not already done
        llm = get_llm() # This function now comes from llm_manager
        if llm:
            parser = JsonOutputParser(pydantic_object=LLMResponseFormat)
        else:
            parser = None # No parser if no LLM

# Call initialization when the module is loaded.
# This is a simple way; a more robust app might use a dedicated init function or class.
initialize_llm_and_parser()

def get_llm_response(user_query: str) -> dict:
    """
    Processes the user query using an LLM to determine intent and extract entities.

    Args:
        user_query: The raw input string from the user.

    Returns:
        A dictionary with 'intent' and 'entities'.
        Returns a default error structure if LLM is not available or an error occurs.
    """
    global llm, parser # Use the globally initialized instances

    if not llm or not parser:
        print("LLM Integration Error: LLM or Parser not initialized. Check LLM configuration and API keys.")
        return {"intent": "error_llm_unavailable", "entities": {}, "error_message": "LLM is not available."}

    # Prompt template instructing the LLM
    # The format_instructions are automatically generated by the JsonOutputParser
    # and tell the LLM how to structure the JSON.
    prompt_template_str = """
    You are an AI assistant for an e-commerce chatbot. Your task is to understand the user's query and extract relevant information.
    Based on the user's query: "{query}", identify the intent and any relevant entities.

    The possible intents are: 'track_order', 'cancel_order', 'greeting', 'goodbye', 'unknown'.
    If the intent is 'track_order' or 'cancel_order', you MUST try to extract an 'order_id'.
    An order ID is typically a mix of letters and numbers (e.g., ORD123, ITEMXYZ, 98765ABC).
    If no specific order ID is mentioned for an order-related intent, do not invent one.

    {format_instructions}

    User Query:
    {query}
    """

    prompt = ChatPromptTemplate.from_messages([
        SystemMessagePromptTemplate.from_template("You are an AI assistant for an e-commerce chatbot. Your task is to understand the user's query and extract relevant information. The possible intents are: 'track_order', 'cancel_order', 'greeting', 'goodbye', 'unknown'. If the intent is 'track_order' or 'cancel_order', you MUST try to extract an 'order_id'. An order ID is typically a mix of letters and numbers (e.g., ORD123, ITEMXYZ, 98765ABC). If no specific order ID is mentioned for an order-related intent, do not invent one."),
        HumanMessagePromptTemplate.from_template("{format_instructions}\n\nUser Query:\n{query}")
    ])

    # Create a chain: prompt -> LLM -> parser
    # Using .from_template for system and human messages to avoid issues with direct string interpolation if not careful.
    chain = prompt | llm | parser

    try:
        format_instructions = parser.get_format_instructions()
        # print(f"DEBUG: Format Instructions for LLM: {format_instructions}") # For debugging the instructions

        # Invoke the chain with the user query and format instructions
        response_data = chain.invoke({
            "query": user_query,
            "format_instructions": format_instructions
        })

        # Ensure 'entities' is always present, even if empty
        if 'entities' not in response_data or response_data['entities'] is None:
            response_data['entities'] = {}

        return response_data

    except Exception as e:
        print(f"LLM Integration Error: Could not process query due to: {e}")
        # Try to get raw response if possible for debugging, but might fail if 'e' is before LLM call
        error_response = {"intent": "error_llm_processing", "entities": {}, "error_message": str(e)}
        # if hasattr(e, 'response') and hasattr(e.response, 'text'):
        #     error_response["raw_llm_output_on_error"] = e.response.text
        return error_response


if __name__ == '__main__':
    print("--- Testing LLM Integration (Real LLM Usage) ---")
    # IMPORTANT: This will make REAL API calls to the configured LLM provider
    # if `config.yaml` is set up and API keys (e.g., OPENAI_API_KEY) are exported.
    # This may incur costs.

    if not llm:
        print("LLM not available (check config.yaml, API keys, and llm_manager.py). Skipping tests.")
    else:
        print(f"Using LLM: {type(llm)}")
        queries = [
            "Hello there!",
            "Can I cancel my order ORD123?",
            "I want to cancel ORD456 please.",
            "cancel order ABC789",
            "Track my package TRK990",
            "What's the status of my order ORD1001?",
            "Where is my order ITEM007?",
            "I need help with order CUST555, can I cancel it?",
            # "Track item XYZ123 and also tell me if I can cancel PQR456", # Ambiguous, LLM might pick one
            "I want to track my shipment.", # Missing order ID
            "Need to cancel an order.",    # Missing order ID
            "What can you do?", # Should be 'unknown' or a generic help intent if defined
            "Thanks, bye!",
            "ORDER CANCEL ORD2000"
        ]

        for query in queries:
            response = get_llm_response(query)
            print(f"Query: \"{query}\" -> Response: {response}")
            # Example of accessing specific parts:
            # print(f"  Intent: {response.get('intent')}, Order ID: {response.get('entities', {}).get('order_id')}")

        print("\n--- Specific Edge Cases ---")
        edge_cases = [
            "cancel",
            "track",
            "ORD123", # Just an ID
            "My order is ORD777, I want to cancel it",
            "For my order TRK001, can you track it?"
        ]
        for query in edge_cases:
            response = get_llm_response(query)
            print(f"Query: \"{query}\" -> Response: {response}")
